### ISSUE TITLE
True and False highlighted instead of true and false

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [purescript-contrib/atom-language-purescript#14]
As the title says, I'm getting "True" and "False" highlighted instead of "true" and "false".

0.13.0 ide-purescript
0.7.0 language purescript 
1.8.0-beta-2 atom

**Comment by hdgarrood** [comment]
I think `True` and `False` should be highlighted differently from most code, because they could be either types or data constructors (and in fact, both of `data True` and `data MyBoolean = True | False` are perfectly fine PS code). However, I suppose that `true` and `false`, being literals, ought to be highlighted in the same way as literals like `0` and `"hi"`. It seems like they're highlighted as ordinary identifiers right now, eg: https://github.com/hdgarrood/purescript-sequences/blob/6a68dda0c9dc77d2cdb9caf890a68983343d0e26/src/Data/Sequence.purs#L187-L190 (although GitHub might have an older version of this highlighter by now).

**Comment by nwolverson** [comment]
I would think `True` and `False` should be highlighted the same as `Foo` and `Bar`, which is as you say, either type or data constructors. Not sure what you mean by differently from most code; only truly built-in things were being highlighted specially as I understand it (much less than the haskell mode).

(The github highlighter should not be *too* out of date in general, I believe there is a pull of all the syntax files on a ~monthly basis)
